from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_PATH = REPO_ROOT / "scripts" / "run_nuclear_local_curvature_no_leakage_prototype.py"


def _load_module():
    spec = importlib.util.spec_from_file_location(
        "run_nuclear_local_curvature_no_leakage_prototype",
        SCRIPT_PATH,
    )
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def _assert_nested_close(left, right) -> None:
    if isinstance(left, dict):
        assert left.keys() == right.keys()
        for key in left:
            _assert_nested_close(left[key], right[key])
        return
    if isinstance(left, list):
        assert len(left) == len(right)
        for left_item, right_item in zip(left, right):
            _assert_nested_close(left_item, right_item)
        return
    if isinstance(left, float):
        assert left == pytest.approx(right, abs=1e-12)
        return
    assert left == right


def test_no_leakage_prototype_imports_cleanly() -> None:
    module = _load_module()

    assert module.AGENT_RUN_ID == "AGENT-RUN-0039"
    assert module.TASK_ID == "TASK-0394"
    assert hasattr(module, "build_metrics")
    assert hasattr(module, "render_report")


def test_no_leakage_variant_panel_covers_required_categories() -> None:
    module = _load_module()
    variants = module._build_variants()

    assert [variant["candidate_id"] for variant in variants] == [
        "LOCAL-CURVATURE-001",
        "LOCAL-NOLEAK-CTRL-001",
        "LOCAL-NOLEAK-CTRL-002",
        "LOCAL-NOLEAK-CTRL-003",
        "LOCAL-NOLEAK-CTRL-004",
        "LOCAL-NOLEAK-ABL-001",
    ]
    assert {
        variant["control_category"]
        for variant in variants
        if variant.get("control_category") is not None
    } == {
        "chain_shuffled",
        "smooth_window",
        "mass_number_only",
        "near_null",
        "self_inclusion_ablation",
    }


def test_build_metrics_records_sandbox_boundary_and_cache_audit() -> None:
    module = _load_module()
    metrics = module.build_metrics()
    summary = metrics["summary"]

    assert metrics["agent_run_id"] == "AGENT-RUN-0039"
    assert metrics["task_id"] == "TASK-0394"
    assert metrics["sandbox_only"] is True
    assert metrics["live_external_fetch_allowed"] is False
    assert summary["canonical_results_changed"] is False
    assert summary["canonical_claims_changed"] is False
    assert summary["prediction_registry_changed"] is False
    assert summary["claim_promotion_allowed"] is False
    assert summary["lane_verdict"] in {"PARTIALLY_VALID", "INCONCLUSIVE", "FALSIFIED"}
    assert metrics["fold_cache_audit"]["passes_per_fold_cache_audit"] is True
    assert metrics["no_leakage_contract"]["baseline_only_neighbor_residuals"] is True
    assert metrics["no_leakage_contract"]["per_fold_neighbor_cache"] is True
    assert metrics["no_leakage_contract"]["target_row_excluded"] is True
    assert metrics["no_leakage_contract"]["holdout_rows_excluded_from_cache"] is True


def test_candidate_and_control_comparison_is_complete() -> None:
    module = _load_module()
    metrics = module.build_metrics()

    comparisons = metrics["candidate_vs_strongest_control"]
    assert len(comparisons) == 1
    row = comparisons[0]
    assert row["candidate_id"] == "LOCAL-CURVATURE-001"
    assert row["primary_strongest_control_id"] in {
        "LOCAL-NOLEAK-CTRL-001",
        "LOCAL-NOLEAK-CTRL-002",
        "LOCAL-NOLEAK-CTRL-003",
        "LOCAL-NOLEAK-CTRL-004",
    }
    assert row["comparable_subset_count"] > 0
    assert 0.0 <= row["subset_win_rate"] <= 1.0


def test_committed_metrics_match_recomputed_summary() -> None:
    module = _load_module()
    committed_path = REPO_ROOT / "agent_runs" / "AGENT-RUN-0039" / "metrics.json"
    if not committed_path.exists():
        pytest.skip("AGENT-RUN-0039 metrics are generated by the task runner")

    committed = json.loads(committed_path.read_text(encoding="utf-8"))
    recomputed = module.build_metrics()

    _assert_nested_close(committed["summary"], recomputed["summary"])
    _assert_nested_close(committed["fold_cache_audit"], recomputed["fold_cache_audit"])
    _assert_nested_close(
        committed["candidate_vs_strongest_control"],
        recomputed["candidate_vs_strongest_control"],
    )


def test_runner_writes_only_sandbox_outputs(tmp_path: Path) -> None:
    module = _load_module()
    targets = {
        "--out": tmp_path / "metrics.json",
        "--report": tmp_path / "report.md",
        "--agent-run": tmp_path / "agent_run.yaml",
        "--limitations": tmp_path / "limitations.md",
        "--preflight": tmp_path / "preflight.md",
        "--review-summary": tmp_path / "review_summary.md",
        "--review": tmp_path / "review.md",
    }
    args: list[str] = []
    for flag, path in targets.items():
        args.extend([flag, str(path)])

    registry_dir = REPO_ROOT / "prediction_registry" / "nuclear_masses"
    before = sorted(path.name for path in registry_dir.iterdir())
    assert module.main(args) == 0
    after = sorted(path.name for path in registry_dir.iterdir())

    for path in targets.values():
        assert path.exists()
    assert before == after
