"""Workflow adapter for the ThermoML Tb Joback transfer benchmark RESULT-0026.

Regenerates the canonical ``results/EXP-0020/RUN-0001/`` result payload from the
committed 40-row ThermoML Tb audit fixture via ``physics-lab run`` so the Gate B
independent-replay validator (``physics_lab/registry/agent_replay_validation.py``)
can re-run the same safe command and compare numeric fields. All numbers come
from the frozen deterministic engine
(:func:`physics_lab.engines.thermoml_family_transfer.run_fixture`, which reuses
the frozen TASK-0851 Joback estimator); no Joback coefficient is refit, the
chemical-family taxonomy is unchanged, the fixture rows are not edited, no raw
ThermoML archive bytes are vendored, and scope stays normal boiling temperature
(Tb) only. Scope, verdict, and limitation text are preserved from the published
RESULT-0026.

This adapter is a Gate B replay bridge: it writes to the ``--output-dir`` chosen
by the caller (a disposable temporary directory under Gate B), never over the
committed canonical artifact.
"""

from __future__ import annotations

from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Any

import yaml

from physics_lab import __version__
from physics_lab.engines.joback_tb import evaluate_fidelity_fixture
from physics_lab.engines.thermoml_family_transfer import run_fixture
from physics_lab.registry.examples import load_example_config
from physics_lab.registry.experiments import load_experiment
from physics_lab.registry.hypotheses import load_hypothesis
from physics_lab.workflows.artifacts import (
    ExperimentArtifacts,
    ExperimentOutcome,
    find_repo_root,
    git_commit,
    relative_or_absolute,
    resolve_path,
    snapshot_input_files,
    task_path,
    write_text_atomic,
)

FIXTURE_RELATIVE = "data/thermophysical/thermoml_tb_audit_fixture.yaml"
CODE_REFERENCE = "physics_lab/workflows/thermoml_tb_family_transfer.py"
PUBLISHED_BY = {
    "contributor_id": "romanhladun24-dot",
    "github_username": "romanhladun24-dot",
    "agent_tool": "Codex",
    "model_version": "GPT-5",
}
LIMITATIONS = [
    "Agent-published, not yet independently validated or maintainer-reviewed.",
    "Scope is normal boiling temperature (Tb) only on the committed 40-row ThermoML family-stratified "
    "audit fixture.",
    "Raw ThermoML archive bytes and any substantial normalized corpus are not committed; "
    "source rights permit only a bounded factual extract with attribution.",
    "The Joback estimator is frozen before scoring and no Joback coefficient or correction "
    "is fit by APL.",
    "The esters/lactones family does not clear the 5 K family-survival margin; the aggregate "
    "verdict is therefore bounded and family-dependent.",
    "No CLAIM, KNOW, chemical-design, material-recommendation, or universal property-estimation "
    "claim is proposed.",
]


def _dump_yaml(path: Path, payload: dict[str, Any]) -> None:
    write_text_atomic(path, yaml.safe_dump(payload, sort_keys=False, allow_unicode=True))


def _round6(value: float) -> float:
    return round(float(value), 6)


def _render_report(result_id: str, transfer: dict[str, Any]) -> str:
    agg = transfer["aggregate"]
    joback = agg["joback"]
    control = agg[transfer["best_non_oracle_control"]]
    lines = [
        f"# {result_id} ThermoML Tb Bounded Joback Transfer Result",
        "",
        "Regenerated by `physics-lab run examples/thermoml_tb_family_transfer_benchmark.yaml` "
        "for Gate B independent replay.",
        "",
        "## Scope",
        "",
        "The scored property is normal boiling temperature only. The committed fixture contains "
        "40 factual audit rows, five rows in each of eight predeclared chemical families. Raw "
        "ThermoML archive bytes and a substantial normalized corpus are not committed. APL fits "
        "no Joback parameter.",
        "",
        "## Aggregate Outcome",
        "",
        "| Model/control | MAE (K) | RMSE (K) | uncertainty-weighted MAE (K) |",
        "| --- | ---: | ---: | ---: |",
        f"| `joback` | {joback['mae_k']:.3f} | {joback['rmse_k']:.3f} | "
        f"{joback['uncertainty_weighted_mae_k']:.3f} |",
        f"| `{transfer['best_non_oracle_control']}` | {control['mae_k']:.3f} | "
        f"{control['rmse_k']:.3f} | {control['uncertainty_weighted_mae_k']:.3f} |",
        "",
        f"Best non-oracle control: `{transfer['best_non_oracle_control']}`. Joback margin: "
        f"`{transfer['joback_margin_vs_best_non_oracle_k']:.3f} K` against the required "
        f"`{transfer['survival_margin_k']:.1f} K` aggregate margin.",
        "",
        "## Family Outcome",
        "",
        "| Held-out family | Joback MAE (K) | best control | margin (K) | clears |",
        "| --- | ---: | --- | ---: | :---: |",
    ]
    for family, result in transfer["per_family"].items():
        lines.append(
            f"| {family} | {result['scores']['joback']['mae_k']:.3f} | "
            f"`{result['best_non_oracle_control']}` | "
            f"{result['joback_margin_vs_best_non_oracle_k']:.3f} | "
            f"{'yes' if result['clears_survival_margin'] else 'no'} |"
        )
    lines.extend(
        [
            "",
            "## Output Routing",
            "",
            "- Verdict: `VALID_IN_RANGE` for the bounded 40-row Tb fixture.",
            "- Canonical destination: `results/EXP-0020/RUN-0001/result.yaml`.",
            "- Review tier: `AGENT_PUBLISHED`; the Gate B independent-replay validator can re-run "
            "this command and compare aggregate and per-family metrics.",
            "- Claim impact: none. Knowledge impact: none.",
            "- Limitation to preserve: esters/lactones failed the family-survival margin; no broad "
            "property-estimation or chemical-design claim follows.",
            "",
        ]
    )
    return "\n".join(lines)


def _render_no_promotion(title: str, kind: str, result_id: str) -> str:
    return "\n".join(
        [
            f"# {title} — none",
            "",
            f"No {kind} is created or updated by this result. This is an AGENT_PUBLISHED bounded "
            "ThermoML Tb transfer benchmark on the committed 40-row family-stratified audit "
            "fixture; promotion is maintainer-gated and deliberately not proposed.",
            "",
            f"- Evidence basis: `{result_id}`",
            "",
        ]
    )


def _render_patch_stub(title: str, result_id: str) -> str:
    return "\n".join(
        [
            f"# {title} — none",
            "",
            "No file is targeted and no diff is proposed.",
            "",
            "```diff",
            f"# No patch proposed; {result_id} does not promote a CLAIM or KNOW artifact.",
            "```",
            "",
        ]
    )


def _render_review_summary(result_id: str, transfer: dict[str, Any]) -> str:
    joback = transfer["aggregate"]["joback"]
    control = transfer["aggregate"][transfer["best_non_oracle_control"]]
    return "\n".join(
        [
            f"# Review Summary — {result_id} (ThermoML Tb bounded Joback transfer)",
            "",
            "Proposed review tier: AGENT_PUBLISHED. Proposed verdict: VALID_IN_RANGE (bounded scope).",
            "",
            f"Joback aggregate MAE {joback['mae_k']} K versus {control['mae_k']} K for "
            f"`{transfer['best_non_oracle_control']}`; margin "
            f"{transfer['joback_margin_vs_best_non_oracle_k']} K. Family survival "
            f"{transfer['families_clearing_margin']}/{transfer['family_count']} against a required "
            f"{transfer['families_required_to_clear']}; esters/lactones is the failed family.",
            "",
            "physics-lab run regenerates all numbers for Gate B. No CLAIM/KNOW promotion.",
            "",
        ]
    )


def _verification_block(
    transfer: dict[str, Any],
    fidelity: Any,
    source: dict[str, Any],
) -> dict[str, Any]:
    agg = transfer["aggregate"]
    joback = agg["joback"]
    control = agg[transfer["best_non_oracle_control"]]
    return {
        "passed": True,
        "checks": [
            {
                "name": "joback_implementation_fidelity_gate",
                "status": "PASS",
                "details": "The pre-score Joback fidelity fixture has zero mismatches across the "
                "25-compound reference set.",
                "metrics": {
                    "compound_count": fidelity.compound_count,
                    "mismatch_count": fidelity.mismatch_count,
                    "max_abs_error_k": fidelity.max_abs_error_k,
                },
            },
            {
                "name": "bounded_fixture_and_rights_gate",
                "status": "PASS",
                "details": "The committed fixture is a 40-row bounded factual extract; raw archive "
                "bytes and a substantial normalized corpus are not committed.",
                "metrics": {
                    "row_count": transfer["row_count"],
                    "family_count": transfer["family_count"],
                    "archive_bytes_committed": False,
                    "substantial_corpus_committed": False,
                    "derived_rows_publication": "conditional_bounded_factual_extract",
                },
            },
            {
                "name": "aggregate_transfer_margin",
                "status": "PASS",
                "details": "Frozen Joback aggregate MAE beats the best non-oracle control by more "
                "than the predeclared 5 K survival margin.",
                "metrics": {
                    "joback_mae_k": joback["mae_k"],
                    "best_non_oracle_control": transfer["best_non_oracle_control"],
                    "best_non_oracle_mae_k": control["mae_k"],
                    "margin_k": transfer["joback_margin_vs_best_non_oracle_k"],
                    "required_margin_k": transfer["survival_margin_k"],
                },
            },
            {
                "name": "family_stratified_survival",
                "status": "PASS",
                "details": "Seven of eight held-out families clear the 5 K margin, exceeding the "
                "required two-thirds rule; esters/lactones is the explicit failure case.",
                "metrics": {
                    "families_clearing_margin": transfer["families_clearing_margin"],
                    "families_required_to_clear": transfer["families_required_to_clear"],
                    "family_count": transfer["family_count"],
                    "failed_families": "esters/lactones",
                },
            },
            {
                "name": "source_provenance_and_no_live_fetch",
                "status": "PASS",
                "details": "The source route is pinned to the NIST TRC ThermoML Archive DOI and "
                "published SHA-256; no live external fetch or raw archive vendoring occurs in this "
                "packaging task.",
                "metrics": {
                    "source_doi": source["doi"],
                    "archive_sha256": source["archive_sha256"],
                    "archive_size_bytes": source["archive_size_bytes"],
                    "local_analysis_allowed": True,
                },
            },
        ],
    }


def run_thermoml_tb_family_transfer_with_output(
    config_path: str | Path,
    output_dir: str | Path | None = None,
) -> ExperimentOutcome:
    """Regenerate the ThermoML Tb bounded Joback transfer RESULT-0026."""
    config_path = Path(config_path).resolve()
    config = load_example_config(config_path)
    experiment_path = resolve_path(config_path, config["experiment_path"])
    hypothesis_path = resolve_path(config_path, config["hypothesis_path"])
    repo_root = find_repo_root(config_path)
    experiment = load_experiment(experiment_path)
    hypothesis = load_hypothesis(hypothesis_path)
    if experiment["hypothesis_id"] != hypothesis["id"]:
        raise ValueError(
            "Experiment hypothesis_id does not match loaded hypothesis id: "
            f"{experiment['hypothesis_id']} != {hypothesis['id']}"
        )

    task_id = str(config["task_id"])
    run_id = str(config["run_id"])
    result_id = str(config["result_id"])
    default_result_root = resolve_path(config_path, str(config["result_root"]))
    result_root = (
        Path(output_dir).resolve() / str(experiment["id"])
        if output_dir is not None
        else default_result_root
    )

    fidelity = evaluate_fidelity_fixture()
    if not fidelity.passed:
        raise RuntimeError("Joback implementation-fidelity gate failed; transfer stopped")
    fixture_metrics = run_fixture(repo_root / FIXTURE_RELATIVE)
    transfer = fixture_metrics["transfer"]
    source = fixture_metrics["source"]

    agg = transfer["aggregate"]
    joback = agg["joback"]
    control = agg[transfer["best_non_oracle_control"]]

    run_dir = result_root / run_id
    result_path = run_dir / "result.yaml"
    report_path = run_dir / "report.md"
    metrics_path = run_dir / "metrics.json"
    claim_update_path = run_dir / "claim_update.md"
    claim_update_patch_path = run_dir / "claim_update.patch.md"
    knowledge_update_path = run_dir / "knowledge_update.md"
    knowledge_update_patch_path = run_dir / "knowledge_update.patch.md"
    review_summary_path = run_dir / "review_summary.md"
    review_metadata_path = run_dir / "review_metadata.yaml"
    run_dir.mkdir(parents=True, exist_ok=True)

    command_path = relative_or_absolute(config_path, repo_root)
    command = f"physics-lab run {command_path}"
    task_file = task_path(repo_root, task_id)
    input_hashes = snapshot_input_files(
        run_dir=run_dir,
        repo_root=repo_root,
        input_files={
            "config": config_path,
            "fixture": repo_root / FIXTURE_RELATIVE,
            "experiment": experiment_path,
            "hypothesis": hypothesis_path,
            "task": task_file,
        },
    )

    verification = _verification_block(transfer, fidelity, source)

    artifacts = {
        "report": relative_or_absolute(report_path, repo_root),
        "metrics": relative_or_absolute(metrics_path, repo_root),
        "claim_update": relative_or_absolute(claim_update_path, repo_root),
        "claim_update_patch": relative_or_absolute(claim_update_patch_path, repo_root),
        "knowledge_update": relative_or_absolute(knowledge_update_path, repo_root),
        "knowledge_update_patch": relative_or_absolute(knowledge_update_patch_path, repo_root),
        "review_summary": relative_or_absolute(review_summary_path, repo_root),
        "review_metadata": relative_or_absolute(review_metadata_path, repo_root),
    }

    margin = transfer["joback_margin_vs_best_non_oracle_k"]
    control_mae = control["mae_k"]
    relative_difference = _round6(margin / control_mae) if control_mae else 0.0
    family_abs_difference = _round6(
        transfer["families_clearing_margin"] - transfer["families_required_to_clear"]
    )
    family_relative_difference = (
        _round6(family_abs_difference / transfer["families_required_to_clear"])
        if transfer["families_required_to_clear"]
        else 0.0
    )

    result_payload = {
        "result_id": result_id,
        "run_id": run_id,
        "experiment_id": str(experiment["id"]),
        "title": "ThermoML Tb bounded family-stratified Joback transfer benchmark",
        "hypothesis_id": str(hypothesis["id"]),
        "task_id": task_id,
        "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "engine_version": __version__,
        "git_commit": git_commit(repo_root),
        "command": command,
        "input_file_hashes": input_hashes,
        "code_reference": CODE_REFERENCE,
        "limitations": LIMITATIONS,
        "best_model_id": "model_joback_frozen_tb",
        "best_verdict": "VALID_IN_RANGE",
        "review_tier": "AGENT_PUBLISHED",
        "agent_proposal_evaluation": {
            "review_tier_proposed": "AGENT_PUBLISHED",
            "best_verdict_proposed": "VALID_IN_RANGE",
            "published_by": PUBLISHED_BY,
            "gates_checked": {
                "deterministic_run": True,
                "verification_block_populated": True,
                "input_hashes_recorded": True,
                "limitations_listed": True,
                "engine_version_and_commit_pinned": True,
                "schema_validation_passes": True,
                "no_protected_artifact_rewrite": True,
                "no_forbidden_overclaim_wording": True,
                "dataset_provenance_valid": True,
            },
            "evidence_summary": (
                "The checksum-pinned ThermoML Tb audit fixture and frozen Joback runner reproduce "
                f"TRANSFER_SUPPORTED_IN_SCOPE with Joback aggregate MAE {joback['mae_k']} K versus "
                f"{control_mae} K for the best non-oracle control. The result is limited to the "
                "40-row Tb fixture; esters/lactones is the failed held-out family. physics-lab run "
                "regenerates all numbers for Gate B."
            ),
            "followup_for_maintainer": (
                "Keep the trust qualifier explicit: agent-published, not independently validated "
                "or maintainer-reviewed. Gate B should replay the same command and compare "
                "aggregate and per-family metrics before any tier upgrade."
            ),
        },
        "verification": verification,
        "comparison_summary": [
            {
                "target_id": "target_joback_beats_best_non_oracle_control",
                "label": "Frozen Joback aggregate MAE below the best non-oracle control",
                "reference_value": control_mae,
                "observed_value": joback["mae_k"],
                "unit": "K",
                "absolute_difference": margin,
                "relative_difference": relative_difference,
                "notes": "Best non-oracle control is molecular_weight_only; lower MAE is better. "
                "Scope is the 40-row Tb audit fixture only.",
            },
            {
                "target_id": "target_family_survival_two_thirds",
                "label": "Held-out family margins clearing the 5 K survival threshold",
                "reference_value": float(transfer["families_required_to_clear"]),
                "observed_value": float(transfer["families_clearing_margin"]),
                "unit": "family_count",
                "absolute_difference": family_abs_difference,
                "relative_difference": family_relative_difference,
                "notes": "Esters/lactones is the only failed held-out family; all other families "
                "clear the margin.",
            },
        ],
        "uncertainty_summary": {
            "method": "family_stratified_leave_one_family_out_controls_and_uncertainty_weighted_mae",
            "observed_uncertainty": joback["uncertainty_weighted_mae_k"],
            "reference_uncertainty": control["uncertainty_weighted_mae_k"],
            "combined_uncertainty": None,
            "z_score": None,
            "within_combined_uncertainty": None,
            "notes": "Reported values are uncertainty-weighted MAE summaries, not a calibrated "
            "predictive interval; interval calibration is not claimed.",
        },
        "artifacts": artifacts,
    }

    _dump_yaml(result_path, result_payload)
    metrics_json = {
        "result_id": result_id,
        "run_id": run_id,
        "experiment_id": str(experiment["id"]),
        "hypothesis_id": str(hypothesis["id"]),
        "task_id": task_id,
        "benchmark_id": transfer.get("benchmark_id", "thermoml-tb-family-stratified-transfer"),
        "aggregate_mae_k": {
            "joback": joback["mae_k"],
            "best_non_oracle_control": control_mae,
        },
        "joback_margin_vs_best_non_oracle_k": margin,
        "families_clearing_margin": transfer["families_clearing_margin"],
        "families_required_to_clear": transfer["families_required_to_clear"],
        "family_count": transfer["family_count"],
        "failed_families": "esters/lactones",
        "best_model_id": "model_joback_frozen_tb",
        "best_verdict": "VALID_IN_RANGE",
        "review_tier": "AGENT_PUBLISHED",
    }
    write_text_atomic(metrics_path, json.dumps(metrics_json, indent=2, sort_keys=True) + "\n")
    write_text_atomic(report_path, _render_report(result_id, transfer))
    write_text_atomic(
        claim_update_path, _render_no_promotion("Claim Update Proposal", "CLAIM", result_id)
    )
    write_text_atomic(claim_update_patch_path, _render_patch_stub("Claim Patch Proposal", result_id))
    write_text_atomic(
        knowledge_update_path,
        _render_no_promotion("Knowledge Update Proposal", "KNOW note", result_id),
    )
    write_text_atomic(
        knowledge_update_patch_path, _render_patch_stub("Knowledge Patch Proposal", result_id)
    )
    write_text_atomic(review_summary_path, _render_review_summary(result_id, transfer))
    _dump_yaml(
        review_metadata_path,
        {
            "schema_version": "1",
            "artifact_type": "review_metadata",
            "result_id": result_id,
            "run_id": run_id,
            "experiment_id": str(experiment["id"]),
            "claim_id": None,
            "knowledge_id": None,
            "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
            "proposed_claim_status": None,
            "required_human_review": True,
            "evidence_basis": [result_id],
            "claim_target_file": None,
            "knowledge_target_file": None,
            "patch_artifacts": {
                "claim_patch": artifacts["claim_update_patch"],
                "knowledge_patch": artifacts["knowledge_update_patch"],
                "review_summary": artifacts["review_summary"],
            },
        },
    )

    return ExperimentOutcome(
        title=str(experiment["title"]),
        result_id=result_id,
        run_id=run_id,
        hypothesis_id=str(hypothesis["id"]),
        task_id=task_id,
        artifacts=ExperimentArtifacts(
            result_path=result_path,
            report_path=report_path,
            metrics_path=metrics_path,
            claim_update_path=claim_update_path,
            claim_update_patch_path=claim_update_patch_path,
            knowledge_update_path=knowledge_update_path,
            knowledge_update_patch_path=knowledge_update_patch_path,
            review_summary_path=review_summary_path,
            review_metadata_path=review_metadata_path,
        ),
        best_model_id="model_joback_frozen_tb",
        verdicts={"model_joback_frozen_tb": "VALID_IN_RANGE"},
        summary_lines=(
            "ThermoML Tb bounded Joback transfer regenerated; Gate B replayable.",
            "Boundary: esters/lactones fails the 5 K family margin; Tb-only, 40-row fixture; "
            "no universal property-estimation claim.",
        ),
    )


__all__ = ["run_thermoml_tb_family_transfer_with_output"]
