"""Helpers for maintainer task closeout checks."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from physics_lab.registry.scientific_memory_integrity import (
    result_artifact_policy_advice,
)
from physics_lab.registry.task_discovery import find_task_files
from physics_lab.registry.tasks import load_task


PUBLIC_STATE_TASK_MARKERS = (
    "agent-run",
    "autonomous",
    "benchmark",
    "campaign",
    "completed experiment",
    "experiment",
    "flagship",
    "holdout",
    "mission",
    "nuclear",
    "public-facing",
    "release",
    "result",
    "scientific",
    "status",
)
PUBLIC_STATE_CLOSEOUT_DOCS = (
    "README.md",
    "docs/status.md",
    "docs/mission-control.md",
    "docs/next-steps.md",
)


@dataclass(frozen=True)
class TaskCloseoutReport:
    """Deterministic snapshot for maintainer closeout review."""

    task_id: str
    task_file: Path
    status: str
    accepted_outputs: tuple[str, ...]
    warnings: tuple[str, ...]
    suggested_actions: tuple[str, ...]


def find_task_file(root: Path, task_id: str) -> Path:
    """Resolve a repository task id to its single task YAML file."""
    matches = find_task_files(root, task_id)
    if not matches:
        raise FileNotFoundError(
            f"No task file found for {task_id} under {root / 'tasks'}"
        )
    if len(matches) > 1:
        rendered_matches = ", ".join(str(path) for path in matches)
        raise ValueError(f"Multiple task files found for {task_id}: {rendered_matches}")
    return matches[0]


def build_closeout_report(root: Path, task_id: str) -> TaskCloseoutReport:
    """Build a deterministic closeout review snapshot for one task.

    Closeout decisions are based on the canonical task YAML status, which is the
    single source of truth. The generated task navigation is regenerated by the
    post-merge Sync Active Board GitHub Action and is not consulted here.
    """
    task_file = find_task_file(root, task_id)
    payload = load_task(task_file)
    status = str(payload["status"])
    accepted_outputs = tuple(str(item) for item in payload.get("accepted_outputs", []))

    warnings: list[str] = []
    suggested_actions: list[str] = []

    if status != "REVIEW_READY":
        warnings.append(
            "Task status is "
            f"{status}, not REVIEW_READY. Closeout normally starts from "
            "REVIEW_READY after merge."
        )

    # Shift-left guard: surface the missing result_artifact_policy before DONE so
    # the no-result check does not first fail at closeout strict validation.
    policy_advice = result_artifact_policy_advice(payload, root_path=root)
    if policy_advice is not None:
        warnings.append(policy_advice)

    if status == "REVIEW_READY":
        suggested_actions.append(
            "Confirm the PR was merged and CI passed before setting the task to DONE."
        )
        suggested_actions.append(
            "Verify accepted outputs exist in main before updating the task file."
        )
        suggested_actions.append(
            "Keep the closeout YAML-only. docs/task-views/*.md are regenerated "
            "automatically on main by the Sync Active Board GitHub Action after "
            "the closeout merges. Run python3 -m physics_lab.cli sync-active-board "
            ". by hand only for explicit audits (APL_ENFORCE_BOARD_STALENESS=1) or "
            "when the action is temporarily disabled."
        )
    elif status == "DONE":
        suggested_actions.append(
            "Confirm the task views and any dry-run notes reflect the merged task."
        )
    else:
        suggested_actions.append(
            "Return the task to REVIEW_READY before maintainer closeout if "
            "implementation is complete."
        )

    suggested_actions.append(
        "Create a follow-up task instead of forcing DONE when accepted outputs "
        "are only partially complete."
    )
    suggested_actions.append(
        "Add a docs/multi-agent-dry-run.md entry only when the merged PR "
        "belongs to a dry run or contributor pilot."
    )
    suggested_actions.append(
        "Closeout publish reminder: closeout edits should not remain only in a "
        "local worktree. After verification, prepare a closeout commit and PR "
        "or ask the maintainer to publish them; do not push or merge without "
        "explicit maintainer authorization."
    )
    if should_review_public_state_docs(payload):
        suggested_actions.extend(render_public_state_doc_checklist())

    return TaskCloseoutReport(
        task_id=task_id,
        task_file=task_file,
        status=status,
        accepted_outputs=accepted_outputs,
        warnings=tuple(warnings),
        suggested_actions=tuple(suggested_actions),
    )


def should_review_public_state_docs(payload: dict) -> bool:
    """Return whether closeout should suggest checking public state docs."""
    parts: list[str] = [
        str(payload.get("id", "")),
        str(payload.get("title", "")),
        str(payload.get("type", "")),
    ]
    task_input = payload.get("input", {})
    if isinstance(task_input, dict):
        parts.append(str(task_input.get("related_domain", "")))
        parts.append(str(task_input.get("planning_context", "")))
        related_objects = task_input.get("related_objects", [])
        if isinstance(related_objects, list):
            parts.extend(str(item) for item in related_objects)
    for key in ("strategy_alignment", "requirements", "accepted_outputs"):
        items = payload.get(key, [])
        if isinstance(items, list):
            parts.extend(str(item) for item in items)

    haystack = " ".join(parts).lower()
    return any(marker in haystack for marker in PUBLIC_STATE_TASK_MARKERS)


def render_public_state_doc_checklist(
    missing_docs: tuple[str, ...] = PUBLIC_STATE_CLOSEOUT_DOCS,
) -> tuple[str, ...]:
    """Return a structured public-doc drift checklist for closeout agents."""
    docs = ", ".join(PUBLIC_STATE_CLOSEOUT_DOCS)
    if missing_docs:
        missing = ", ".join(missing_docs)
        checklist = (
            "Public docs drift checklist: compare "
            f"{docs} against authoritative task, experiment, result, agent-run, "
            f"and mission state. Missing from this closeout diff: {missing}."
        )
    else:
        checklist = (
            "Public docs drift checklist: public-facing state docs were touched "
            f"({docs}); confirm experiment counts, active flagship campaigns, "
            "result surfaces, near-term priorities, and release-gate wording "
            "still match authoritative structured state."
        )

    policy = (
        "Closeout docs-sync policy: routine closeout may update task status, "
        "generated task navigation (docs/task-views/*.md), "
        "and CONTEXT.md automatically; edit README/status/mission-control/"
        "next-steps only when the current task explicitly asks for public-doc "
        "sync. Otherwise update an existing docs-sync task or create a "
        "follow-up task."
    )
    return (checklist, policy)


def render_closeout_report(
    report: TaskCloseoutReport,
    *,
    suggest: bool = False,
    root: Path | None = None,
) -> str:
    """Render a stable text report for CLI or script usage."""
    root_path = root.resolve() if root is not None else None
    try:
        task_file_display = (
            report.task_file.resolve().relative_to(root_path).as_posix()
            if root_path
            else str(report.task_file)
        )
    except ValueError:
        task_file_display = str(report.task_file.resolve())

    lines = [
        f"Task: {report.task_id}",
        f"Task file: {task_file_display}",
        f"Current status: {report.status}",
        "Accepted outputs:",
    ]

    if report.accepted_outputs:
        lines.extend(f"- {item}" for item in report.accepted_outputs)
    else:
        lines.append("- <none parsed>")

    lines.append("Warnings:")
    if report.warnings:
        lines.extend(f"- {item}" for item in report.warnings)
    else:
        lines.append("- none")

    lines.append("Suggested closeout actions:")
    lines.extend(f"- {item}" for item in report.suggested_actions)

    if suggest:
        lines.append("Suggested file updates (not applied):")
        if report.status == "REVIEW_READY":
            lines.append("- Change task status from REVIEW_READY to DONE after merge verification.")
            lines.append(
                "- Do not run python3 -m physics_lab.cli sync-active-board . in the closeout PR. The Sync Active Board GitHub Action regenerates generated task navigation on main after the closeout merges."
            )
        else:
            lines.append(
                "- No direct file update is suggested until the task reaches "
                "REVIEW_READY and merge is confirmed."
            )

    return "\n".join(lines)
